print('           #     #  ######  #     #  #     #')
print('           ##   ##  #       ##    #  #     #')
print('           # # # #  #       # #   #  #     #')
print('           #  #  #  ####    #  #  #  #     #')
print('           #     #  #       #   # #  #     #')
print('           #     #  #       #    ##  #     #')
print('           #     #  ######  #     #   ##### ')
print('____________________________________________________________')
print('|                         Services                         |')
print('|                                                          |')
print('|   .oOo.------------.[ Slow Hammer ].------------.oOo.    |')
print('|                                                          |')
print('|   .oOo.------------.[   IP Info   ].------------.oOo.    |')
print('|                                                          |')
print('|   .oOo.------------.[    E-Hack   ].------------.oOo.    |')
print('|                                                          |')
print('|   .oOo.------------.[  Host info  ].------------.oOo.    |')
print('|                                                          |')
print('|                   Open directory (cd)                    |')
print('|                                                          |')
print('|      SlowHammer |  ipinfo     |  ehack     | host        |')
print('|      hammer.py  |  ipinfo.py  |  ehack.py  | host.py     |')
print('|__________________________________________________________|')
print('Slow Hammer - Dos/DDoS http flood script (GET,POST)...')
print('IP Info - get information about IP...')
print('E-Hack - sending sms for different emails...')
print('Host info - get information about URL...')
print('*************************************************************')


